# Generated by Django 5.0.2 on 2024-02-10 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0002_alter_class_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolSystem.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolSystem.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolSystem.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolSystem.student')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolSystem.schedule')),
            ],
        ),
    ]
